theme: jekyll-theme-minimal
title: Windows set-up automatization
description: Set-up your Windows environment from a fresh installation, with just a line of code!
logo: theme-logo.png
show_downloads: false
google_analytics: UA-56422469-2